# Generated by Django 3.2.3 on 2021-05-28 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название', max_length=63)),
                ('description', models.TextField(help_text='Описание', max_length=255)),
                ('author', models.CharField(help_text='Автор', max_length=63)),
                ('timestamp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название', max_length=63)),
                ('description', models.TextField(help_text='Описание', max_length=255)),
                ('author', models.CharField(help_text='Автор', max_length=63)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Calendar.task')),
            ],
        ),
    ]
