# Generated by Django 3.2.3 on 2021-05-28 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0002_auto_20210528_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='calendar',
        ),
        migrations.AddField(
            model_name='task',
            name='calendar',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Calendar.calendar'),
            preserve_default=False,
        ),
    ]
