# Generated by Django 3.2.3 on 2021-05-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0003_auto_20210528_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar.css',
            name='path',
            field=models.CharField(default=0, help_text='Путь по которому получают этот календарь', max_length=63),
            preserve_default=False,
        ),
    ]
